// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynyldzuxegiiqmjnwrmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlueWxkenV4ZWdpaXFtam53cm1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMTY1NTIsImV4cCI6MjA2Njg5MjU1Mn0.SsLCdnu1rtrHWLmF7joa1v3jhzvWBR5PdlxgTnKx4Dc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});